### PR TITLE
Fix #53, support component initialization

### LINKED ISSUE #53: Support Component initialization

### PR DESCRIPTION
**Pull request by paf31**
@garyb @natefaubion @jdegoes Could you please review?

This supports initialization by adding an init hook, and a new type of `Attr`.

There is also an example in `examples/ajax`.

### CODE REVIEW

**Comment by garyb** [comment]
:+1: 

My only question would be, do you think having the "is-init" `Boolean` as the argument is worth having, instead of just filtering out the updates? It's sort of leaking `virtual-dom` internals to `Attr`, as for other renderers it'd we'd probably have to go out of our way to make it ever fire in the non-init case.

**Comment by paf31** [comment]
@garyb Yes I think you're right. I don't see any use case for an "update hook". Anyone? Otherwise, I can change this and merge it in.

**Comment by cryogenian** [comment]
Firing event after component rerender can be very useful for communication with outside libs. I.e. chart rerender or something.

**Comment by cryogenian** [comment]
Or maybe it would be better to add additional hook for rerendering and filter initializing hook to only first run

**Comment by garyb** [comment]
I think that would be preferrable.

When would the update hook fire also? I'm not sure the default behaviour of virtual dom retriggering the hook is necessarily the same thing as what we'd want here.

**Comment by cryogenian** [comment]
I think update hook should be fired after rerender element just like in vdom. 
Moreover there should be something like `unhook` or `componentDismounted`.

**Comment by garyb** [comment]
I thought `hook` only fires if the value associated with it changes?

**Comment by cryogenian** [comment]
Don't know precisely about it, I thought that they fire after rerender.

**Comment by cryogenian** [comment]
found this https://github.com/Matt-Esch/virtual-dom/blob/master/docs/hooks.md

**Comment by paf31** [comment]
Yes, that's the doc I've been working from.

**Comment by jdegoes** [comment]
It seems to me we need:

 * On initialization (a one-time event)
 * On (re) render (occurs potentially multiple times)
 * On destruction (a one-time event)

Anything else?

**Comment by paf31** [comment]
Just curious - I (sort of) see the need for a initialization hook, but why do we need to have hooks for updates and destruction? It seems to go against the abstraction we've built a little. When would you need to know that a pure component (not a widget) was rerendered?

**Comment by jdegoes** [comment]
@paf31 Well, what if you wanted to fire off an event to persist some data on destruction? 

I'm not sure about re-rendering, but I assume it would be useful in some circumstances if your pure component embeds an impure one. @cryogenian / @garyb ?

**Comment by paf31** [comment]
:+1: for destruction, but I think I'd prefer that users use widgets if they need update notifications. The only use case I can think of is to sync a widget's state with the state of the component. Pure components should use virtual-dom to operate at a higher level of abstraction than individual updates IMO.

**Comment by jdegoes** [comment]
:+1: Sounds good to me, pending comments from everyone else.

**Comment by garyb** [comment]
I missed the component/widget distinction originally - I'd agree with @paf31 that you'd probably only need update/destruction in widgets.

**Comment by cryogenian** [comment]
The use case of that rerender hook is reuse not widget js components (i.e. bootstrap's tooltip, tab, popover etc).
We definitely can provide all this functionallity by halogen (or bootstrap-halogen) but there is much more other libs, that can be used without adding any code.

**Comment by paf31** [comment]
Wouldn't all of those be the init hook though?

**Comment by cryogenian** [comment]
Yes, all of those can be the init hook :smile: 
I have no other comments then

**Pull request merged**
