### PR TITLE
Synchronous variant of `appendTo`.

### PR DESCRIPTION
**Pull request by fisx**
See commit message.

I did this to solve an immediate issue I had; if you don't like the code as is, but have ideas what you would like instead, I am happy to give this a bit more work.

### CODE REVIEW

**Comment by zudov** [comment]
Heh. Initially we only had a synchronous version, but changed it to asynchronous to make it smoother.

IMHO, it would be ideal to make `appendTo` synchronous and just provide an `onLoad` thingy.

**Comment by fisx** [comment]
Done.  It's a bit more disruptive, but I like this solution better.

**Comment by garyb** [comment]
Can we keep the `MonadEff` constraint on `appendTo` and `appendToBody` please?

**Comment by fisx** [comment]
Yes, I wanted to, but I got an error that I don't remember.  I'll try again later and come back with more data if I fail again.

**Comment by garyb** [comment]
Ok, thanks! I think all it needs is a sprinkling of `liftEff` to make it work out, although the `callback` will probably have to be `Eff` as I didn't use the constraint when defining `addEventListener`.

**Comment by fisx** [comment]
Hm, that really wasn't that hard.  (-:

**Comment by fisx** [comment]
(I looked at the travis log, but don't understand it.  It looks like `npm install` choked on installing...  what?)

**Comment by zudov** [comment]
Try to restart the build (close pull request and then open it)

**Comment by jonsterling** [comment]
No need to close the PR, I have restarted the build

**Comment by fisx** [comment]
oops, sorry...

**Comment by garyb** [comment]
Looks good, thanks! One last thing, can you squash the commits please?

**Comment by fisx** [comment]
aw, i was being so tidy about the individual commits.  (-:

but it's your code, so here you go.  thanks for talking me through this!

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
