### PR TITLE
Render queuing

### LINKED ISSUE #398: DOMException when using input onBlur events
The following example throws `Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?` when pressing `Enter` on the `input` element (only in Chrome, not in Firefox, and not when pressing "Stop Edit" or deselecting the `input` element):

```purescript
module Main where

import Prelude
import Halogen as H
import Halogen.HTML as HH
import Halogen.HTML.Events as HE
import Halogen.HTML.Properties as HP
import Control.Monad.Aff (Aff)
import Control.Monad.Eff (Eff)
import DOM.Event.KeyboardEvent (code)
import Data.Maybe (Maybe(..))
import Halogen.Aff (awaitBody, runHalogenAff)
import Halogen.Aff.Effects (HalogenEffects)
import Halogen.VDom.Driver (runUI)

data Query a
  = StartEdit a
  | SetValue String a
  | StopEdit a

type State =
  { editing :: Boolean
  , value :: String
  }

app :: H.Component HH.HTML Query Unit Void App
app = H.component
  { initialState: const
      { editing: false
      , value: ""
      }
  , render
  , eval
  , receiver: const Nothing
  }

render :: State -> H.ComponentHTML Query
render st = HH.div_
  [ case st.editing of
      true ->
        HH.input
        [ HP.value st.value
        , HE.onValueInput (HE.input SetValue)
        , HE.onKeyDown \e -> case code e of
            "Enter" -> Just (H.action StopEdit)
            _       -> Nothing
        , HE.onBlur (HE.input_ StopEdit)
        ]
      false ->
        HH.text st.value
  , HH.button
    [ HE.onClick $ HE.input_ (if st.editing then StopEdit else StartEdit) ]
    [ HH.text (if st.editing then "Stop Edit" else "Start Edit") ]
  ]

eval :: Query ~> H.ComponentDSL State Query Void App
eval = case _ of
  StartEdit next -> do
    H.modify _{ editing = true }
    pure next
  SetValue val next -> do
    H.modify _{ value = val }
    pure next
  StopEdit next -> do
    H.modify _{ editing = false }
    pure next

type AppEffects = HalogenEffects ()
type App = Aff AppEffects
    
main :: Eff AppEffects Unit
main = runHalogenAff $ do
  body <- awaitBody
  runUI app unit body
```

I did some research and it seems this is somehow because removing an element from the DOM fires an `onblur` event on it (see [this SO answer](http://stackoverflow.com/a/22934552/3176849)). Also the [MDN node.removeChild() doc](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild) says:

> If child is actually not a child of the element node, the method throws an exception. This will also happen if child was in fact a child of element at the time of the call, but was removed by an event handler invoked in the course of trying to remove the element (eg, blur.)

Is this something that can be taken care of in `halogen-vdom`?

### PR DESCRIPTION
**Pull request by garyb**
Should fix #398

### CODE REVIEW

**Comment by themoritz** [comment]
Yep, this fixes #398 for me :tada:

**Comment by garyb** [comment]
How about #402? :smile:

**Comment by themoritz** [comment]
Negative :cry:

**Comment by garyb** [comment]
@natefaubion how does this version look?

**Comment by themoritz** [comment]
@garyb commit 7a92a7d reintroduces the onblur problem.

**Comment by garyb** [comment]
@themoritz can you try this again on your #402 case? I think we might have it this time.

**Comment by garyb** [comment]
:smile:

**Comment by themoritz** [comment]
Ok, 1a19db3 fixes it again :joy:

**Comment by garyb** [comment]
not

**Pull request merged**
