### PR TITLE
Bottom-Up approach to explaining Halogen

### PR DESCRIPTION
**Pull request by JordanMartinez**
As described [in my comment](https://github.com/slamdata/purescript-halogen/issues/528#issuecomment-407833179)

I'm still working on the event handling part. I ran out of time today.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Note: the `recursiveQuery` function described in the `Evaluating Recursive Queries` section results in a compiler error for `HH.button`.

**Comment by JordanMartinez** [comment]
From slack:
> kadblas [3:12 PM]
> Halogen question here. Is there a way to query the view for information during runtime? For example, if I create a `div` in `render`, is there a way to get the width of that div during runtime? If so, how?
> 
> justinw [3:13 PM]
> easy way is through refs
> - https://github.com/justinwoo/purescript-web-audio-player-demo/blob/6f6b692ea83e840d39b32f2bd7db4a7965f44ca7/src/Main.purs#L82
> - https://github.com/justinwoo/purescript-web-audio-player-demo/blob/6f6b692ea83e840d39b32f2bd7db4a7965f44ca7/src/Main.purs#L133
> 
> garyb [3:15 PM]
> example in here too https://github.com/slamdata/purescript-halogen/blob/v4.0.0/examples/ace/src/AceComponent.purs#L57
>
> kadblas [3:17 PM]
> Excellent. Thanks @justinw & @garyb

This PR should extract this code into a pattern to follow.

**Comment by AlexaDeWit** [comment]
Just wanted to say, as a Halogen user... thanks for working on this!

**Comment by JordanMartinez** [comment]
@AlexaDeWit Thanks! I've been wanting to finish documenting it, but I'm waiting for the `5.0.0` release.

Also, I've since learned how `VariantF` works. If one used `VariantF` as their query type, one could mix in `preventDefault` and `stopPropagation` into their `eval` function easily.

**Comment by JordanMartinez** [comment]
Closing this since I've created the `learn-halogen` repo that is even better than this.

**Pull request closed without merging**
