### PR TITLE
Fix broken example called "components" according to sync with docs files

### PR DESCRIPTION
**Pull request by sdolidze**
docs and examples were out of sync, "components" example was not even buildable. Minor change to sync example with docs.

### CODE REVIEW

**Comment by garyb** [comment]
Hey, thanks - it looks like you've reverted some changes in the example here though. Master is the "next" version, so the `ChildSlots` business was correct, it's just the `package.json` that needed updating.

**Comment by sdolidze** [comment]
Thanks for the quick reply :) I'm a PureScript newbie trying to make sense of how Halogen works. I tried to build the project with ChildSlots and it did not work (including changing the package.json). Is that the intended behaviour?

**Comment by garyb** [comment]
If you've checked out `master`, you should be able to build the example from the root of the project with `npm run example-components` instead of building it per example.

Perhaps we should remove the per-example `package.json`s, as in times like this where `master` is ahead of the released version they won't work properly, unless you do a bunch of non-obvious stuff to make it symlink bower dependency for Halogen instead. 🤔 

Another option is to check out the v4.0.0 tag instead of `master`, and then you should be able to run the individual examples as standalone projects too. I'd perhaps suggest doing that for now, since the docs are only updated for v4 still! 🙂

**Comment by sdolidze** [comment]
Now it makes total sense :) When I saw `master` and `next` branches, I assumed next was ahead. I assumed that `ChildSlots` was the old approach, when it was the new one :) (It's my third day using PureScript, so I guess it's understandable).

I totally agree, removing per-example package.json would create less room for confusion for newbies like me. I guess this PR makes no sense.

Would you accept PR deleting per-example package.json-s? Or is it something that you need to think about first?

**Comment by JordanMartinez** [comment]
In your PR, you should probably include a note in the examples' ReadMe about checking out the latest release tag before trying out the examples because I don't think this is the first time this issue has appeared.

**Comment by JordanMartinez** [comment]
@sdolidze If you haven't already, you might want to check out [the flowchart I made in 528](https://github.com/slamdata/purescript-halogen/issues/528#issuecomment-400071113)

**Comment by sdolidze** [comment]
@JordanMartinez thanks for the flowchart, it's quite handy.

Adding note in README to check out latest release tag will not help for the time being. I just checked out `V4.0.0` and it will not build, because package.json has older version of purescript (0.11.7 instead of 12.2.0).

I totally agree with @garyb's suggestion that we should remove `package.json`-s altogether as it creates more problems than provides use for beginners.

Should I submit a PR deleting `package.json`-s in all `examples` folders and updating `REAMDE.md`-s to build only from root of the project?

**Comment by sdolidze** [comment]
@JordanMartinez I'm consistently getting same error messages, even when running in clean docker container. It could be the case that I'm doing something wrong. here is my `Dockerfile` and output that it wrote, please have a look. https://gist.github.com/sdolidze/7d11d72f6ebbbaa9ab7fc246500fb053

**Comment by sdolidze** [comment]
This PR does not make much sense, therefor I'm closing it. In my opinion, the best solution to this problem is to remove per-example `package.json`-s. Here is a related PR: #560

**Pull request closed without merging**
