### PR TITLE
update purescript-generics dependencies in examples to version 0.7.0+

### PR DESCRIPTION
**Pull request by savuori**
fixes compilation errors with psc 0.7.6.1

### CODE REVIEW

**Comment by garyb** [comment]
Thanks! I'd been meaning to get around to this. I'll merge once Travis completes.

**Comment by garyb** [comment]
Ah, I think the failures are because the behaviour of `bower link` changed recently to not also trigger a `bower install`, so the scripts in `package.json` will need updating. 

Could you make that change too please (just update the `bower link purescript-halogen` part to `bower link purescript-halogen && bower install` in each of the build scripts), and bump the compiler dependency to `^0.7.6` while you're at it. Thanks!

**Comment by savuori** [comment]
Sure, I'll do that.

**Comment by garyb** [comment]
Thanks! :+1:

**Pull request merged**
