### PR TITLE
New readme and some updated documentation

### PR DESCRIPTION
**Pull request by garyb**
There's one code change too: I did away with the `ParentComponent` synonym as it was unhelpful in real work situations. It just made for prettier demos when you only have one-component-deep installation.

Please let me know if there's anything wrong, unclear, missing, or that could otherwise be improved!

Then.... :ship: :shipit: :fireworks: :tada: :confetti_ball:

### CODE REVIEW

**Comment by jonsterling** [comment]
Really nice work! 

One small issue though: the AJAX example fails to build with `Unknown value E.onValueQuery` (https://travis-ci.org/slamdata/purescript-halogen/builds/85769015#L1915).

**Comment by jonsterling** [comment]
Also, might be worthwhile to bump the version of node that is used in the Travis build to quell these complaints: https://travis-ci.org/slamdata/purescript-halogen/builds/85769015#L97

**Comment by beckyconning** [comment]
Looks gorgeous! Perfectly happy with this after the issues @jonsterling raised are resolved. Let me know if you want any help writing a roadmap for moving forwards from 0.5.

**Comment by garyb** [comment]
Thanks! Have fixed the things, will merge and release once Travis passes :smile:

**Comment by jonsterling** [comment]
:fireworks: :exclamation:

**Pull request merged**
