### PR TITLE
Added some bootstrap classes and very basic styles 

### PR DESCRIPTION
**Pull request by cryogenian**

### CODE REVIEW

**Comment by jdegoes** [comment]
Review / merge by @paf31

**Comment by cryogenian** [comment]
I've removed ```Halogen.Themes.Bootstrap3.Glyphicons``` and generated ```Halogen.Themes.Bootstrap3``` and ```Halogen.Themes.Foundation5``` by this script: https://gist.github.com/cryogenian/c19cfd13e949435f54a5, then I've removed some clashes to make ```gulp make``` works

**Comment by paf31** [comment]
Looks great! I actually quite like the idea of separating out the glyphicons stuff, but it probably makes generating the code more difficult.

Would you please add your script under `scripts/` so that I can regenerate this later if needed?

**Comment by paf31** [comment]
@cryogenian If/once you do that, please do merge your branch. I'm out for the rest of the day today. Thanks!

**Pull request merged**
