### PR TITLE
Clean up unnecessary stuff

### PR DESCRIPTION
**Pull request by garyb**
Surprise! :tada: 40% of `Component`'s type variable are unnecessary.

### CODE REVIEW

**Comment by beckyconning** [comment]
😍

**Comment by jonsterling** [comment]
wow!

**Comment by jdegoes** [comment]
:gift:

**Comment by garyb** [comment]
This happened in two phases:

1. When we removed `installL`/`installR` etc. storing `peek` in the component became unnecessary, and therefore the `o` type variable.
2. When we moved to inline installation the `p` type variable became unnecessary, as the `render` type's `p` is always `Void` after install.

**Pull request merged**
