### PR TITLE
update for Purescript v0.9.1

### PR DESCRIPTION
**Pull request by deamme**
"purescript-stalling-coroutines" needs to be updated for v0.9.1 as well for this to work.

### CODE REVIEW

**Comment by deamme** [comment]
"pulp test" works, but all the examples doesn't:
 - npm run example-ace
 - npm run example-ajax
 - npm run example-components
 - npm run example-counter
 - npm run example-deep-peek
 - npm run example-interpret
 - npm run example-intro
 - npm run example-keyboard-shortcuts
 - npm run example-lifecycle
 - npm run example-multi-component
 - npm run example-todo

**Comment by garyb** [comment]
Ok thanks, I'll take a look.

**Comment by deamme** [comment]
Are you working on it? We could divide it.

**Comment by garyb** [comment]
Well, one thing that's wrong is that `purescript-ace` will need updating first for that example to work. The others I've mostly done with - I'll make a PR to your branch.

**Comment by deamme** [comment]
Oh haha, I'm done with them all except purescript-ace.

**Comment by deamme** [comment]
I didn't do the warnings though..

**Comment by garyb** [comment]
That's fine, I can just run through those before making the final release.

**Comment by deamme** [comment]
Shall I work on a purescript-ace PR?

**Comment by garyb** [comment]
If you don't mind doing so, that would be great!

**Comment by deamme** [comment]
Okay, I'm on it.

**Comment by garyb** [comment]
Just to let you know, there's a problem in `purescript-ace` that I'm trying to fix before tagging the new version of that (nothing to do with the updates as far as I can see, it's possibly always been broken). I've got some other things I need to deal with first, but should return to it later today.

**Comment by garyb** [comment]
Ok, `purescript-ace` has been released at last!

**Comment by deamme** [comment]
Should be alright now.

**Comment by garyb** [comment]
Nice, thanks a lot!

**Comment by garyb** [comment]
I just made the release (v0.9.0). Thanks again for your work on this :thumbsup:

**Comment by deamme** [comment]
Awesome. I'm glad that I could help 😃

**Pull request merged**
