### PR TITLE
EQ, Semigroup and Show instances or URL

### PR DESCRIPTION
**Pull request by passy**
I don't know of this is something you'd like to have for simple wrappers.

By the way, is something like `NewtypeDeriving` somewhere on the roadmap for PS? :)

### CODE REVIEW

**Comment by garyb** [comment]
:+1:

**Comment by paf31** [comment]
:+1:

**Comment by jdegoes** [comment]
Thanks @passy!

**Comment by jdegoes** [comment]
Ultimately it would be nice to have `purescript-url` which has URL parser, uses Pathy's `Path` type for the path component, represents query string parameters using `StrMap String` or something similar, etc. This `URL` type can contain a lot of things which have no relation to URLs. :smile: Also occurs to me it should probably be a `newtype` rather than a `data` declaration -- if someone wants to change it the next time they're working in that file.

**Comment by garyb** [comment]
I've made a start on that: https://github.com/garyb/purescript-uri but it doesn't break things up that finely yet.

Happy to move that repo to `slamdata` also, if you like?

**Comment by jdegoes** [comment]
[Yes, please!](https://github.com/slamdata/purescript-uri)

**Pull request merged**
