### PR TITLE
Add no-op to HalogenF

### PR DESCRIPTION
**Pull request by jonsterling**
@garyb I forgot to open a PR for this; anyway, this is just a preliminary implementation to see if it solves the problem you were having. If we actually want to use this, I can go and make the other changes we discussed (namely, making `HalogenF` a proper sum type and collapsing all the coproducts into it).

### CODE REVIEW

**Comment by garyb** [comment]
No problem! I'd started using the branch directly from your repo anyway. It's looking good so far!

**Comment by jonsterling** [comment]
Oh dear lord, I think I killed it... :wink: Will need to add some `Inject` instances or something.

**Comment by garyb** [comment]
Restarted the build as it wasn't obvious what the error was to me - just a hiccup?

And actually this isn't quite what I had in mind either! I was thinking we could just squash everything into a single `HalogenF` type:

``` purescript
data HalogenF s f g a
  = Get (s -> a)
  | Modify (s -> s) a
  | Subscribe (EventSource f g) a
  | Empty
  | Run (g a) -- ok, not sure what this should be called... QueryHF in your version I guess?
```

Not sure if this would make the implementation any simpler though, so no biggie if not.

**Comment by jonsterling** [comment]
@garyb Oh, sorry, I had misunderstood! I could certainly try something like this if you want. Do you think it will result in a performance improvement?

**Comment by garyb** [comment]
I'm not really sure it will make that much of a difference - just thought it might have made the implementation of interpreters/natural transformations for `HalogenF` a bit simpler.

**Comment by jonsterling** [comment]
@garyb Ah, I see. I think that the baby step that I took has simplified the interpreters and transformations a fair bit (or, if not simplified, at least clarified). I can see if the further-squashed version you propose would make things even clearer—it seems like it might, at the expense of a bit of implementation modularity.

**Comment by jonsterling** [comment]
@garyb I thought about it a little more, and I think that squashing this further into a single type will complicate things more than simplify them; for instance, currently we are able to hide the implementations of various natural transformations inside modules like `*.State` and `*.Subscribe`, and just use them as we please... 

Can you think of an example of where squashing it into the single type would make things easier or simpler? I probably missed a number of thing, just since I'm not super familiar with this codebase.

**Comment by jdegoes** [comment]
> Can you think of an example of where squashing it into the single type would make things easier or simpler? 

It would make things faster. If there are modularity tradeoffs, however, it may not be worth it.

**Comment by jonsterling** [comment]
@jdegoes If it's a significant performance improvement, I think it's probably worth it. Halogen's internals are gnarly enough that I won't cry too many tears about losing a little bit of implementation modularity (which is not as important as interface modularity anyway).

**Comment by garyb** [comment]
I didn't have anything in mind in particular, just wondered if it would help. It sounds like this is probably the right level of fusion to stop at by the sounds of it :smile: (unless we have some serious performance issue it would help with, but I doubt that, queries are never going to be super fast given that we're in Aff, etc.)

**Comment by jonsterling** [comment]
All right; I'll leave it up to @garyb :smile:

**Comment by jdegoes** [comment]
By the way, I suggest instead of naming the empty constructor `Empty`, you name it `Halt` (since that's effectively what it is).

**Comment by jonsterling** [comment]
@jdegoes Good idea, I suppose it is terminal...

**Comment by garyb** [comment]
Once this passes :+1: for jondentation, :+1: for the `HalogenF` changes.

**Comment by jonsterling** [comment]
thanks @garyb ! :smile:

**Pull request merged**
