### PR TITLE
Use ListT in Event monad instead of MaybeT in Handler functor

### LINKED ISSUE #57: Make EventHandler a monad transformer
By using `WriterT`. This will avoid the need for `pure <<< pure` etc.

### PR DESCRIPTION
**Pull request by paf31**
Reverts slamdata/purescript-halogen#61

### CODE REVIEW

**Comment by paf31** [comment]
I'll extend this PR with the `ListT` approaches.

**Comment by paf31** [comment]
@jdegoes I think this is as good as it's going to get. It's not quite what I was after, but it supports the use cases we need.

I tried using something like `FreeT` to define a `Producer` monad, which worked nicely, but the types didn't fit well with `Component`, so I ditched it.

As a compromise, I added the `andThen` combinator, which allows us to use `ListT` a bit more like `FreeT`.

Let me know what you think.

**Comment by jdegoes** [comment]
This looks good to me. The specialization to `ListT (Aff eff)` definitely reduced the complexity of many type signatures, and allows us to get a (potentially effectful) `cancel` for "free" (`pure empty`).

I know you didn't want to prematurely specialize to `Aff` but leave the door open to other approaches. This seems to model the domain very well (zero or more outputs for every input), and has clear and obvious semantics (asynchronous possibly empty stream of outputs), but is certainly less general-purpose than a `MonadDriver` approach. What are your thoughts?

**Comment by paf31** [comment]
I think it works nicely. In the end, it doesn't matter too much, since we can map a monad morphism over a component anyway, so if the user wants to use a different monad, they can, but I think this gives a nice default.

**Comment by jdegoes** [comment]
:shipit:

**Pull request merged**
