### PR TITLE
First pass at component module

### LINKED ISSUE #44: Composing two Views is somewhat problematic due to event handlers
Given two trivial views with different state types:
```purescript
data Count = Inc | Dec

app1 :: PureView Count
app1 = render <$> stateful 0 update where
  render count =
    H.p_
      [ H.text (show count)
      , H.button (A.onclick (const $ pure Inc)) [ H.text "+" ]
      , H.button (A.onclick (const $ pure Dec)) [ H.text "-" ]]
  update count Inc = count + 1
  update count Dec = count - 1

app2 :: PureView String
app2 = render <$> stateful "" (flip const) where
  render val =
    H.p_
      [ H.input (A.type_ "text" <> A.value val <> A.onInput pure) []
      , H.text val ]
```

I want to compose these together so they are shown one after another (so basically I want to `<>` their HTML). These seems like something you could easily do with Profunctor and Apply (split the combined states, and then append the HTML) but the problem is that the SF/SF1 instances don't touch the event handlers, which would have to know about the new combined state. You can't rmap an additional map on to the HTML to modify the resulting handlers because you don't have access to the composite state to do an update. Also I think you'd have to continually pay for each map, which would likely be bad for app written from lots of smaller parts. What's the best way to go about something like this?

### PR DESCRIPTION
**Pull request by paf31**
Resolves #44, #45, #48.

@jdegoes Could you please review?

/cc @natefaubion @garyb @cryogenian

### CODE REVIEW

**Comment by cryogenian** [comment]
What does `combine` do? Does it make one component from two siblings?

**Comment by cryogenian** [comment]
What does `combine` do? Does it make one component from two siblings?

**Comment by paf31** [comment]
Yes exactly.

**Comment by jdegoes** [comment]
I'll review this more thoroughly over the weekend, but a ton of things seem to get simpler and more composable. The examples seemed to get simpler or not change, except for the `pure (pure .)` stuff which could probably use a helper or two (especially for `component'`, it'd be nice to have helpers).

Again, no final thoughts on this until I do a more thorough review, but what are your initial thoughts??

**Comment by paf31** [comment]
> but what are your initial thoughts??

I like it :)

I need to try using `compose` for something - so far, I've only typechecked it.

**Comment by jdegoes** [comment]
> I need to try using compose for something - so far, I've only typechecked it.

Then of course it's going to work, right? :smile: 

The other thing I was thinking, re: compose: maybe it would be possible to use placeholder to allow embedding a component *inside* a component? That would be insanely awesome.

**Comment by paf31** [comment]
It should be possible using `graft` I think if the types line up.

**Comment by natefaubion** [comment]
I'll try to play with it some this weekend as well.

>The other thing I was thinking, re: compose: maybe it would be possible to use placeholder to allow embedding a component inside a component? That would be insanely awesome.

This is desirable, and I think you'll immediately want something analogous to Angular's transclusion. Ie, you'll want to run a component where you give it `HTML` that retains a binding to its original component. Whereas in Angular you want it to stay bound to the original `$scope` (and not the child's `$scope`), here you'd want handlers and state to route back to the original component.

**Comment by natefaubion** [comment]
One thing missing is a way to provide a component an initial input, to say kick off a request to fetch data on load.

**Comment by paf31** [comment]
@natefaubion Doesn't `onload` give you that?

**Comment by natefaubion** [comment]
The onload event doesn't work for any arbitrary element. It's for body and things that load external resources like img or script.

**Comment by paf31** [comment]
Ok, but it seems like there must be some way that could be solved using events. It seems like a bit of a shame to introduce effects at the top level. Using `Aff` would make the initial render potentially delayed for example.

**Comment by natefaubion** [comment]
I mean, you can do it if you bundle everything into a widget and use init. But I don't think there's going to be a quick, widely supported DOM event you can hook into.

**Comment by paf31** [comment]
I think this is close enough to merge, yes? We can probably figure something out for initialization later on, given that the internals of the module aren't exported anyway.

**Comment by natefaubion** [comment]
Providing support for [hooks](https://github.com/Matt-Esch/virtual-dom/blob/7cd99a160f8d7c9953e71e0b26a740dae40e55fc/docs/hooks.md) as well as widgets would be useful and allow you to implement initialization, though I don't know how much of the virtual-dom API you want to leak through.

**Comment by paf31** [comment]
Agreed, and maybe we can wrap them in a restricted way like we have for widgets. Could you maybe give a sketch of how you see hooks working for initialization?

I think the tricky bit is going to be keeping a sane API/ `Component` is already impure because of the `m` argument, so maybe we just have to wrap the whole signal function with an extra `m`. My plan was to just bubble everything to `runUI` where the initializers would get run.

**Comment by jdegoes** [comment]
> Ok, but it seems like there must be some way that could be solved using events. It seems like a bit of a shame to introduce effects at the top level.

:+1: for this, even if we have to fake our own `oninit`-style event (i.e. intercept and generate it). Wrapping the whole thing in effects is not a good solution as it could lead to blocking the UI indefinitely. The current formulation is carefully constructed so that effects may block UI updates but may not block UI rendering, which is a very important property to preserve.

**Comment by jdegoes** [comment]
Also, I know this is already merged, but :+1:. I will have a few comments or questions on helper functions, component nesting, etc., but overall this change seemed to do a lot of good so I'm in favor of it.

**Pull request merged**
