### PR TITLE
Added inputR for easier recursive query evaluation

### PR DESCRIPTION
**Pull request by JordanMartinez**
This adds the function I came up with in #426.

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Closing this one as well as I'm not sure this really is necessary/helpful anymore.

**Comment by cdupont** [comment]
Hello, I'm also trying to stop event propagation. Why is this not necessary anymore?

**Comment by garyb** [comment]
`Action`s are no longer kinded `Type -> Type` so this helper isn't required in the example situation any more.

This wasn't directly related to stopping propagation, it was just an example of the pattern where this function would have been useful.

**Comment by garyb** [comment]
If you're just looking for help on how to stop propagation, then this is the function you're looking for: https://pursuit.purescript.org/packages/purescript-web-events/docs/Web.Event.Event#v:stopPropagation 🙂. Use it with `liftEffect` in the action handler that receives the `Event`. 

There's a similar example for `preventDefault` here: https://github.com/purescript-halogen/purescript-halogen/blob/master/examples/keyboard-input/src/Main.purs#L59, although this also required coercing the `KeyboardEvent` to `Event` (`KE.toEvent`) which won't be necessary if the handler you're using raises `Event`.

**Pull request closed without merging**
