### PR TITLE
Switch EventSource to use purescript-stalling-coroutines

### LINKED ISSUE #233: Event sources aren't filterable
Event sources are producers from `purescript-coroutines`, but these cannot be filtered. A (pure) producer is guaranteed to always have a value; however, most browser-related event streams do not have this property, and so it appears that "waiting on" a value that may never come has been factored into `AVar` in the `Aff` monad. That is, emptiness for producer is implemented using an effect at present, it would appear.

That was a sufficient means to deal with the fact that (for instance) a JavaScript event listener will not always be firing, but I still think the use of `Producer` is kind of unsatisfactory, since it seems to mandate that *all* events from an `EventStream` be handled; in practice, this means adding no-ops to your query algebra for no good reason.

It may be possible to "filter" an event stream by again using `AVar` and `Aff` in the same way as was done above, but this seems kind of anticompositional and difficult, especially in a real world application, you almost *always* want to filter an event stream (or, at least, say "I won't respond to this event").

One option would be to add a new type like `Producer`, but which uses something with a `Stall` constructor instead of just `Emit`. I'm also open to other suggestions; what do people think?

@garyb @jdegoes @beckyconning @cryogenian

### PR DESCRIPTION
**Pull request by jonsterling**
This will allow users to filter event sources (see [`Control.Coroutine.Stalling.filter`](https://github.com/slamdata/purescript-stalling-coroutines/blob/master/docs/Control/Coroutine/Stalling.md#filter)). This is meant to resolve #233.

### CODE REVIEW

**Comment by garyb** [comment]
Perhaps we could include an example too?

**Comment by jonsterling** [comment]
@garyb sure! Maybe I'll write up a quick keyboard shortcut example.

**Comment by jonsterling** [comment]
@garyb @beckyconning When you get a chance, can you let me know what you think about this? I've added an example w/ keyboard shortcuts.

**Comment by garyb** [comment]
Does `purescript-dom` not provide a way of doing the keyboard event stuff yet?

Either way, looks good to me!

**Comment by jonsterling** [comment]
@garyb Oh neat! I didn't realize `purescript-dom` was as powerful as it is; I think it should be possible to reconstruct that example code using it.

**Comment by garyb** [comment]
It might be missing a few things that would make it possible, but it's supposed to cover the majority of the DOM and HTML APIs, so hopefully it's doable! If not we can perhaps add whatever is missing.

**Comment by jonsterling** [comment]
I'll switch it over to use `dom`, and if there's anything missing, I'll file a ticket and add it.

**Comment by jonsterling** [comment]
@garyb Hmm, I just looked into it and actually, it will probably be more work to use `purescript-dom` than it's worth. Apparently, `keyCode` is not standard and `purescript-dom`'s README says that only standard properties will be supported. Some use of the FFI is, then, inevitable I think, so it might be worthwhile to just keep the example super simple.

What do you think?

**Comment by garyb** [comment]
I remember now, yeah, seems the keyboard stuff is in a mess at the moment. Let's go with this for now then, when browsers are sorted out in 10 years time or something we can use the spec'd version then :wink:

**Comment by jonsterling** [comment]
Cool, sounds good!

**Comment by garyb** [comment]
I'll make a release when #238 is in, unless we need it before then. If so, please go ahead and make a new one yourself - I guess the menu/keyboard shortcut stuff requires this?

**Pull request merged**
